apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
    jaeger-infra: jaeger-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jaeger
      release: jaeger
      jaeger-infra: jaeger-pod
  template:
    metadata:
      labels:
        app: jaeger
        release: jaeger
        jaeger-infra: jaeger-pod
    spec:
      containers:
        - name: jaeger-all-in-one
          image: "jaegertracing/all-in-one:1.47"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
            - name: MEMORY_MAX_TRACES
              value: "{{ .Values.memory_max_traces }}"
          readinessProbe:
            httpGet:
              path: "/"
              port: 16686
            initialDelaySeconds: 5
          resources:
{{ toYaml .Values.jaeger.resources | indent 12 }}
  {{- with .Values.jaeger.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
