## Настройки jaeger
jaeger:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 8Gi
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: monitoring
  service:
    name: jaeger-nodeport
## Порт для доступа к jaeger при выключенном ingress
    nodePort: 30005
  ingress:
## включение host в ingress
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
## аннотации для работы cert-manager
#      certmanager.io/cluster-issuer: letsencrypt
    hosts:
## домен (FQDN), по которому будет доступна система
      - host: example.ru
        paths:
          - path: /
            pathType: ImplementationSpecific
## включение шифрования, при использовании cert-manager указать используемый secretName letsencrypt
#    tls:
#      - secretName: example-ru-cert
#        hosts:
#          - example.ru
## включить создание secret с собственными сертификатами
## указать путь до сертификата в строках key: и cert:
  secret:
    enabled: false
    key: "files/my_cert.key"
    cert: "files/my_cert.crt"
## Чтобы предотвратить проблему нехватки памяти задайте целочисленное значение трассировки 
  memory_max_traces: 150000
## количество реплик для обеспечения высокой доступности
  replicaCount: 1
## параметры подключения к приватному registry
#  image:
## адрес и путь для приватного registry
#    repository: registry.example.com/jaeger
#    tag: "1.47"
## секрет с правами доступа к приватному registry должен быть создан вручную, зашифрованный в Base64
#    pullSecrets:
#      - myRegistryKeySecretName
