  db:
## строки подключения (сonnection strings) для подключения к БД
##
## строки ниже заполнены для elma365-dbs, установленного в пространство имен default в ClusterMode
## замените при необходимости
##
## расшифровка:
## '<connection>://<username>:<password>@<servicename>.<namespace>.svc.<cluster.local>:<port>/<database>?<options>'
## <connection>    - тип строки подключения: postgresql, mongodb, redis, amqp
## <servicename>   - название service в кластере Kubernetes
## <namespace>     - пространство имен, в которое устрановлена база данных
## <cluster.local> - домен кластера, по умолчанию cluster.local
##
## строка подключения к БД Postgres, формат: postgresql://user:password@hostname:5432/databaseName
    psqlUrl: 'postgres://postgres:pgpassword@postgres.elma365-dbs.svc.cluster.local:5432/elma365?sslmode=disable'
## строка подключения к БД Postgres только для чтения, формат: postgresql://user:password@hostname:5432/databaseName
## имя секрета со строкой подключения к БД Postgres, зашифрованной в Base64 (ключ PSQL_URL)
#    psqlSecret: elma365-custom-db-connections
    roPsqlUrl: ''
## ClusterMode - следующая строка используется для PostgreSQL в Cluster Mode
#    roPsqlUrl: 'postgres://postgres:pgpassword@postgres-read.default.svc.cluster.local:5432/elma365?sslmode=disable'
## имя секрета со строкой подключения к БД Postgres только для чтения, зашифрованной в Base64 (ключ RO_POSTGRES_URL)
#    roPsqlSecret: elma365-custom-db-connections
## cтрока подключения к БД MongoDB для приложения, формат: mongodb://user:password@hostname:27017/databaseName
    mongoUrl: 'mongodb://elma365:mongopassword@mongo.elma365-dbs.svc.cluster.local:27017/elma365?ssl=false&replicaSet=rs0&readPreference=secondaryPreferred'
## имя секрета со строкой подключения к БД MongoDB для приложения, зашифрованной в Base64 (ключ MONGO_URL)
#    mongoSecret: elma365-custom-db-connections
## cтрока подключения к БД MongoDB для сервера авторизации, формат: mongodb://user:password@hostname:27017/databaseName
    vahterMongoUrl: 'mongodb://elma365:mongopassword@mongo.elma365-dbs.svc.cluster.local:27017/elma365?ssl=false&replicaSet=rs0&readPreference=secondaryPreferred'
## имя секрета со строкой подключения к БД MongoDB для сервера авторизации, зашифрованной в Base64 (ключ VAHTER_MONGO_URL)
#    vahterMongoSecret: elma365-custom-db-connections
## mongoUrl и vahterMongoUrl могут быть одинаковыми, коллекции внутри бд не пересекаются
## cтрока подключения к Redis, формат: redis://user:password@redis.local:6379/databaseName
    redisUrl: 'redis://redis.elma365-dbs.svc.cluster.local:6379/0'
## имя секрета со строкой подключения к Redis, зашифрованной в Base64 (ключ REDIS_URL)
#    redisSecret: elma365-custom-db-connections
## cтрока подключения к Rabbit, формат amqp://user:password@hostname:5672/vhost
    amqpUrl: 'amqp://elma365:rmqpassword@rabbitmq.elma365-dbs.svc.cluster.local:5672/elma365'
## имя секрета со строкой подключения к Rabbit, зашифрованной в Base64 (ключ AMQP_URL)
#    amqpSecret: elma365-custom-db-connections
##
## настройки подключения к S3 хранилищу файлов
    s3:
      method: PUT
      accesskeyid: PZSF73JG72Ksd955JKU1HIA
      secretaccesskey: aFDkj28Jbs2JKbnvJH678MNwiz88zKjsuNBHHs
      bucket: s3elma365
      backend:
        address: 192.168.31.140
        region: us-east-1
      ssl:
        enabled: "false"
## имя секрета с подключением к S3 хранилищу файлов, зашифрованной в Base64
## (ключи S3_BACKEND_ADDRESS, S3_REGION, S3_KEY, S3_SECRET, S3_BUCKET, S3_SSL_ENABLED, S3_UPLOAD_METHOD)
#    s3Secret: elma365-custom-db-connections
