jaeger:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 8Gi
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: monitoring
  service:
    name: jaeger-nodeport
    nodePort: 31119
  ingress:
    enabled: false
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
#      certmanager.io/cluster-issuer: letsencrypt
    hosts:
      - host: example.ru
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: example-ru-cert
        hosts:
          - example.ru
  secret:
    enabled: false
    key: "files/my_cert.key"
    cert: "files/my_cert.crt"
  memory_max_traces: 150000
  replicaCount: 1
  image:
    repository: registry.example.com/jaeger
    tag: "1.47"
    pullSecrets:
      - myRegistryKeySecretName
