apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger-daemon-agent
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
spec:
  selector:
    matchLabels:
      app: jaeger
      release: jaeger
      jaeger-infra: agent-instance
  template:
    metadata:
      labels:
        app: jaeger
        release: jaeger
        jaeger-infra: agent-instance
    spec:
      containers:
      - name: agent-instance
        image: jaegertracing/jaeger-agent:1.47
        command:
        - "/go/bin/agent-linux"
        - "--reporter.type=grpc"
        - "--reporter.grpc.host-port=jaeger-collector.monitoring.svc:14250"
        - "--reporter.grpc.retry.max=100"
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - name: admin
          containerPort: 14271
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            path: /
            port: admin
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          httpGet:
            path: /
            port: admin
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "staging"
          effect: "NoSchedule"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
