apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  labels:
    app: jaeger
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      name: http
  {{- else }}
  type: NodePort
  ports:
    - port: 16686
      targetPort: 16686
      protocol: TCP
      nodePort: 30666
      name: http
  {{- end }}
  selector:
    app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: monitoring
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
    jaeger-infra: jaeger-service
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    app: jaeger
    jaeger-infra: jaeger-pod
    release: jaeger
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: monitoring
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
    jaeger-infra: collector-service
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: jaeger-collector-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: metrics
    port: 14269
    protocol: TCP
    targetPort: 14269
  selector:
    app: jaeger
    release: jaeger
    jaeger-infra: jaeger-pod
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: monitoring
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
    jaeger-infra: agent-service
spec:
  ports:
  - name: agent-zipkin-thrift
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: agent-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: agent-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  clusterIP: None
  selector:
    app: jaeger
    release: jaeger
    jaeger-infra: jaeger-pod
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-zipkin
  namespace: monitoring
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
    jaeger-infra: zipkin-service
spec:
  ports:
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app: jaeger
    release: jaeger
    jaeger-infra: jaeger-pod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    created-by: addon-operator
    release: jaeger
    heritage: Tiller
    module: {{ $.Chart.Name }}
  name: jaeger-agent-monitoring
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 14271
    protocol: TCP
    targetPort: 14271
  selector:
    app: jaeger
    jaeger-infra: agent-instance
    release: jaeger
  sessionAffinity: None
